embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: 'BPR'
neg_sampling:
  uniform: 1
repeatable: True
eval_batch_size: 2048
eval_args:
  split: { 'LS': 'valid_and_test' }
  order: TO
  mode: full